all: calc1 hijo1 calc3 calc4

calc1: calc1.c
	gcc -o calc1 calc1.c
	
hijo1: hijo1.c
	gcc -o hijo1 hijo1.c
	
calc3: calc3.c
	gcc -o calc3 calc3.c
	
calc4: calc4.c
	gcc -o calc4 calc4.c
	
clean:	
	rm -f -r calc1 calc3 hijo1 calc4
