all: p1 subp1 p2 p3 subp2 p4 prueba1 prueba2

p1: p1.c
	gcc -o p1 p1.c
	
subp1: subp1.c
	gcc -o subp1 subp1.c
	
p2: p2.c
	gcc -o p2 p2.c
	
p3: p3.c
	gcc -o p3 p3.c

subp2: subp2.c
	gcc -o subp2 subp2.c
	
p4: p4.c
	gcc -o p4 p4.c
	
prueba1: prueba1.c
	gcc -o prueba1 prueba1.c
	
prueba2: prueba2.c
	gcc -o prueba2 prueba2.c
	
clean:	
	rm -f -r p1 subp1 p2 p3
